FROM ft-rails:on-build
EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

# rails is a command that manages ruby-web things
# The s is an alias/shorthand for server
# The -b option binds Rails to the specified IP
# The -p tells it which port to run on

# so to check the working web-app go to:
# 0.0.0.0:3000
